version: "3"
services:
    postgres:
        container_name: postgres
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./data:/data/db:Z
        # logging:
        #     driver: none
        healthcheck:
            test: nc -z 5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: feedbacc

    adminer:
        depends_on:
            - postgres
        image: adminer
        restart: always
        ports:
            - 8080:8080

    app:
        tty: true
        stdin_open: true
        container_name: feedbacc_app
        build:
            context: ./
        volumes:
            - ./:/usr/app
            - /usr/app/node_modules
        depends_on:
            - postgres
        ports:
            - "5000:5000"
            - "9229:9229"
            - "5858:5858"
        restart: on-failure
        environment:
            - DATABASE_URL=postgres://root:admin@postgres:5432/feedbacc

        entrypoint: wait-for-it postgres:5432 -- yarn dev:debug
